---
- hosts: all
  become: true
  tasks: 
    - name: update repository index
      apt: 
        update_cache: yes
        when: ansible_distribution == 'Ubuntu'
    
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
        when: ansible_distribution in ["Ubuntu", "Debian"]
    
      
    - name: add php support for apache
      apt: 
        name: libapache2-mod-php
        state: latest 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '8.2'